---
title: "Lab 06 - Functions and iterations"
author: "Xiangyu hu"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )
```


## Exercise 1

```{r}
# Do some preliminary investigations & cleaning
diamonds %>%
  filter(depth_pct == 0) %>%
  count()

diamonds %>%
  filter(length_mm == 0) %>%
  count()

diamonds %>%
  filter(width_mm == 0) %>%
  count()


diamonds %>%
  filter(depth_mm == 0) %>%
  count()

diamonds %>%
  filter(table_pct == 0) %>%
  count()
```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)

# Overall table_mm arithmetic mean?
mean_table_mm <- diamonds %>%
  summarise(mean(table_mm)) %>%
  print()






# table_mm arithmetic mean within each clarity category
mean_ec_table_mm <- diamonds %>%
  group_by(clarity) %>%
  summarise(mean(table_mm)) %>%
  print()





```

_For each clarity with numbered 2, the average table length tends to be higher._

## Exercise 3

_Do derivation on paper, unless you know how to write LaTeX code_


## Exercise 4

```{r}
# Write gmean() command
gmean <- function(x){
  sum_lnx <- sum(log(x))
  x_g <- exp(mean(sum_lnx))
  return(x_g)
}


```

## Exercise 5

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", '7', "8")
)


 #Create for loop to test gmean() on the above examples
#for(i in test_data){
  #print(gmean(i))
#}

```


## Exercise 6

```{r}
# Copy gmean() from Ex4 and edit it to check the input
gmean <- function(x){
  if( any(x <= 0) ){
  warning("<ERROR MESSAGE>")
  return(NaN)}
  sum_lnx <- sum(log(x))
  x_g <- exp(sum_lnx/length(x))
  return(x_g)
}




# Copy your code from Ex 5 to test your new command
test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", '7', "8")
)
#for(i in test_data){
  #print(gmean(i))
#}



```


## Exercise 7

```{r}
# Overall table_mm geometic mean?
diamonds %>%
  filter(depth_pct != 0,
         table_pct != 0,
         length_mm != 0,
         width_mm != 0,
         depth_mm != 0) %>%
  mutate(table_mm = table_pct * width_mm / 100) %>%
  summarise(gmean(table_mm))







# table_mm geometic mean within each clarity category
diamonds %>%
  filter(depth_pct != 0,
         table_pct != 0,
         length_mm != 0,
         width_mm != 0,
         depth_mm != 0) %>%
  mutate(table_mm = table_pct * width_mm / 100) %>%
  group_by(clarity) %>%
  summarise(gmean(table_mm))





```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition
gmean2 <- function(x){
  g_2 = prod(x)^(1/length(x))
  return(g_2)
}
test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", '7', "8")
)
#for(i in test_data){
  #print(gmean2(i))
#}



```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean
hmean <- function(x){
  
}






```
